#baseURL = "/"
baseURL = "https://www.joseoc.com/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Josefo developer"
theme = "docdock"
#theme = "hugo-theme-learn"
#themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

googleAnalytics = "UA-108826494-1"

pygmentsStyle = "vim" #"monokai"
pygmentsUseClassic = false # to use Chroma (syntax highlighter by Go) instead of pygments (python)
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = ""

# To build the project into this folder (docs is the one used by github to create the static website)
# publishDir = "docs"

[blackfriday]
  angledQuotes = true
  hrefTargetBlank = true

[params]
  editURL = "https://github.com/jose-oc/josefo-developer/blob/master/content/"
  description = "Josefo developer. IT notes"
  author = "Jose OC"
  showVisitedLinks = true
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight" # ordersectionsby = "title"

  # Syntax highlight
  highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter

  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = ""
  themeStyle = "original" # "original" or "flex" # default "original"
  [params.ga]
    async = true

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/jose-oc/josefo-developer"
weight = 10

# [[menu.shortcuts]]
# name = "<i class='fa fa-camera'></i> CV"
# url = "cv"
# weight = 15

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

# [[menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30

[Languages]
[Languages.en]
title = "Josefo dev"
weight = 1
languageName = "English"

[Languages.es]
title = "Programador Josefo"
weight = 2
languageName = "Español"

[[Languages.es.menu.shortcuts]]
pre = "<h3>Más</h3>"
name = "<i class='fa fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/jose-oc/josefo-developer"
weight = 10

# [[Languages.es.menu.shortcuts]]
# name = "<i class='fa fa-camera'></i> CV"
# url = "/cv"
# weight = 15

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Documentation Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

# [[Languages.es.menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> Créditos"
# url = "/credits"
# weight = 30