baseURL = "https://jose-oc.github.io/josefo-developer/"
languageCode = "en-us"
title = "Josefo developer"
theme = "hugo-theme-learn"

# To build the project into this folder (docs is the one used by github to create the static website)
publishDir = "docs"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]